name: dnt-hyttesok

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  cron:
    name: run-bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun index.ts
        env:
          AIRTABLE_SECRET: ${{ secrets.AIRTABLE_SECRET }}
          AIRTABLE_APP: ${{ secrets.AIRTABLE_APP }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_TABLE }}
          SLACK_URL: ${{ secrets.SLACK_URL }}